### ISSUE TITLE
Example Using Actix

### ISSUE THREAD

**Issue by devanlooches** [alexkehayias/woz#10]
Hello,
I love this tool.
Would it be possible to use Actix?
If so how would I do that?
Thank you!

**Comment by alexkehayias** [comment]
Hi @devanlooches, the PWAs that `woz` outputs are static files. As such, they can be served by whatever you want (e.g. S3, Netlify, Vertx, etc.). I won't be putting together any specific server guides, but a quick search shows [these docs](https://actix.rs/docs/static-files/).
