### ISSUE TITLE
cargo install woz fails

### ISSUE THREAD

**Issue by ukscone** [alexkehayias/woz#2]
the 

cargo install woz 

stage fails with the following errors

`   Compiling woz v1.3.0
     Running `rustc --edition=2018 --crate-name woz /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/main.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=ffe7b18f845be88d -C extra-filename=-ffe7b18f845be88d --out-dir /tmp/cargo-installAcBr4U/release/deps -L dependency=/tmp/cargo-installAcBr4U/release/deps --extern clap=/tmp/cargo-installAcBr4U/release/deps/libclap-14b70eb97c104272.rlib --extern failure=/tmp/cargo-installAcBr4U/release/deps/libfailure-193f49b871f65d17.rlib --extern flate2=/tmp/cargo-installAcBr4U/release/deps/libflate2-9ef39741ad174fc4.rlib --extern futures=/tmp/cargo-installAcBr4U/release/deps/libfutures-caaaf3872a2ec828.rlib --extern handlebars=/tmp/cargo-installAcBr4U/release/deps/libhandlebars-30ef2c84e67b772a.rlib --extern lazy_static=/tmp/cargo-installAcBr4U/release/deps/liblazy_static-539e359bfc4230fa.rlib --extern rand=/tmp/cargo-installAcBr4U/release/deps/librand-f1fa76ea9e6ce95e.rlib --extern regex=/tmp/cargo-installAcBr4U/release/deps/libregex-1b5c7a4766c5e6ae.rlib --extern ring=/tmp/cargo-installAcBr4U/release/deps/libring-1b523d73e0f03889.rlib --extern rusoto_cognito_identity=/tmp/cargo-installAcBr4U/release/deps/librusoto_cognito_identity-899d54a6e76cf9d8.rlib --extern rusoto_cognito_idp=/tmp/cargo-installAcBr4U/release/deps/librusoto_cognito_idp-1e7836d198728ead.rlib --extern rusoto_cognito_sync=/tmp/cargo-installAcBr4U/release/deps/librusoto_cognito_sync-d0fc804f1b991958.rlib --extern rusoto_core=/tmp/cargo-installAcBr4U/release/deps/librusoto_core-699037ea7a8e8a8c.rlib --extern rusoto_credential=/tmp/cargo-installAcBr4U/release/deps/librusoto_credential-f4e3d94b27bbbe27.rlib --extern rusoto_s3=/tmp/cargo-installAcBr4U/release/deps/librusoto_s3-d0533deabc86b7e1.rlib --extern serde=/tmp/cargo-installAcBr4U/release/deps/libserde-f77b282e7358a738.rlib --extern serde_derive=/tmp/cargo-installAcBr4U/release/deps/libserde_derive-8024251e4e20fa18.so --extern serde_json=/tmp/cargo-installAcBr4U/release/deps/libserde_json-58cdb2f6e29663f6.rlib --extern stderrlog=/tmp/cargo-installAcBr4U/release/deps/libstderrlog-b90f7bd9177aeb82.rlib --extern termion=/tmp/cargo-installAcBr4U/release/deps/libtermion-97cf9f21453e0b58.rlib --extern tokio=/tmp/cargo-installAcBr4U/release/deps/libtokio-1311dd2c294633ca.rlib --extern toml=/tmp/cargo-installAcBr4U/release/deps/libtoml-5f2733f6a66dc821.rlib --cap-lints allow -L native=/tmp/cargo-installAcBr4U/release/build/backtrace-sys-f2f2f81888d48990/out -L native=/tmp/cargo-installAcBr4U/release/build/miniz-sys-272895524a4507ac/out -L native=/tmp/cargo-installAcBr4U/release/build/ring-751e42fec2dca871/out`
error: environment variable `WOZ_WEB_SCHEME` not defined
 --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:8:26
  |
8 | pub const SCHEME: &str = env!("WOZ_WEB_SCHEME");
  |                          ^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_WEB_NETLOC` not defined
 --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:9:26
  |
9 | pub const NETLOC: &str = env!("WOZ_WEB_NETLOC");
  |                          ^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_USER_POOL_URL` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:10:33
   |
10 | pub const USER_POOL_URL: &str = env!("WOZ_USER_POOL_URL");
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_IDENTITY_POOL_ID` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:11:36
   |
11 | pub const IDENTITY_POOL_ID: &str = env!("WOZ_IDENTITY_POOL_ID");
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLIENT_ID` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:12:29
   |
12 | pub const CLIENT_ID: &str = env!("WOZ_CLIENT_ID");
   |                             ^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_S3_BUCKET_NAME` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:13:34
   |
13 | pub const S3_BUCKET_NAME: &str = env!("WOZ_S3_BUCKET_NAME");
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_ENCRYPTION_PASSWORD` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:17:39
   |
17 | pub const ENCRYPTION_PASSWORD: &str = env!("WOZ_ENCRYPTION_PASSWORD");
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_ENCRYPTION_SALT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:18:35
   |
18 | pub const ENCRYPTION_SALT: &str = env!("WOZ_ENCRYPTION_SALT");
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:20:64
   |
20 | pub static DEFAULT_PROJECT_LIB_RS: &str = include_str!(concat!(env!("WOZ_PROJECT_ROOT"), "/examples/seed-app/src/lib.rs"));
   |                                                                ^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:22:58
   |
22 | pub static LANDING_PAGE_CSS: &str = include_str!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/styles/landing_page.css"));
   |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:31:72
   |
31 | static DEFAULT_ICON_48X48: &'static [u8; 831] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/48x48.png"));
   |                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:32:73
   |
32 | static DEFAULT_ICON_72X72: &'static [u8; 1196] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/72x72.png"));
   |                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:33:73
   |
33 | static DEFAULT_ICON_96X96: &'static [u8; 1538] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/96x96.png"));
   |                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:34:75
   |
34 | static DEFAULT_ICON_144X144: &'static [u8; 2217] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/144x144.png"));
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:35:75
   |
35 | static DEFAULT_ICON_168X168: &'static [u8; 2566] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/168x168.png"));
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:36:75
   |
36 | static DEFAULT_ICON_192X192: &'static [u8; 2870] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/192x192.png"));
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:37:75
   |
37 | static DEFAULT_ICON_512X512: &'static [u8; 8042] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/512x512.png"));
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:40:75
   |
40 | static DEFAULT_ICON_152X152: &'static [u8; 2321] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/152x152.png"));
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:41:75
   |
41 | static DEFAULT_ICON_167X167: &'static [u8; 2489] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/167x167.png"));
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `WOZ_CLI_PROJECT_ROOT` not defined
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:42:75
   |
42 | static DEFAULT_ICON_180X180: &'static [u8; 2717] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/180x180.png"));
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 20 previous errors

error: failed to compile `woz v1.3.0`, intermediate artifacts can be found at `/tmp/cargo-installAcBr4U`

Caused by:
  Could not compile `woz`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name woz /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/main.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=ffe7b18f845be88d -C extra-filename=-ffe7b18f845be88d --out-dir /tmp/cargo-installAcBr4U/release/deps -L dependency=/tmp/cargo-installAcBr4U/release/deps --extern clap=/tmp/cargo-installAcBr4U/release/deps/libclap-14b70eb97c104272.rlib --extern failure=/tmp/cargo-installAcBr4U/release/deps/libfailure-193f49b871f65d17.rlib --extern flate2=/tmp/cargo-installAcBr4U/release/deps/libflate2-9ef39741ad174fc4.rlib --extern futures=/tmp/cargo-installAcBr4U/release/deps/libfutures-caaaf3872a2ec828.rlib --extern handlebars=/tmp/cargo-installAcBr4U/release/deps/libhandlebars-30ef2c84e67b772a.rlib --extern lazy_static=/tmp/cargo-installAcBr4U/release/deps/liblazy_static-539e359bfc4230fa.rlib --extern rand=/tmp/cargo-installAcBr4U/release/deps/librand-f1fa76ea9e6ce95e.rlib --extern regex=/tmp/cargo-installAcBr4U/release/deps/libregex-1b5c7a4766c5e6ae.rlib --extern ring=/tmp/cargo-installAcBr4U/release/deps/libring-1b523d73e0f03889.rlib --extern rusoto_cognito_identity=/tmp/cargo-installAcBr4U/release/deps/librusoto_cognito_identity-899d54a6e76cf9d8.rlib --extern rusoto_cognito_idp=/tmp/cargo-installAcBr4U/release/deps/librusoto_cognito_idp-1e7836d198728ead.rlib --extern rusoto_cognito_sync=/tmp/cargo-installAcBr4U/release/deps/librusoto_cognito_sync-d0fc804f1b991958.rlib --extern rusoto_core=/tmp/cargo-installAcBr4U/release/deps/librusoto_core-699037ea7a8e8a8c.rlib --extern rusoto_credential=/tmp/cargo-installAcBr4U/release/deps/librusoto_credential-f4e3d94b27bbbe27.rlib --extern rusoto_s3=/tmp/cargo-installAcBr4U/release/deps/librusoto_s3-d0533deabc86b7e1.rlib --extern serde=/tmp/cargo-installAcBr4U/release/deps/libserde-f77b282e7358a738.rlib --extern serde_derive=/tmp/cargo-installAcBr4U/release/deps/libserde_derive-8024251e4e20fa18.so --extern serde_json=/tmp/cargo-installAcBr4U/release/deps/libserde_json-58cdb2f6e29663f6.rlib --extern stderrlog=/tmp/cargo-installAcBr4U/release/deps/libstderrlog-b90f7bd9177aeb82.rlib --extern termion=/tmp/cargo-installAcBr4U/release/deps/libtermion-97cf9f21453e0b58.rlib --extern tokio=/tmp/cargo-installAcBr4U/release/deps/libtokio-1311dd2c294633ca.rlib --extern toml=/tmp/cargo-installAcBr4U/release/deps/libtoml-5f2733f6a66dc821.rlib --cap-lints allow -L native=/tmp/cargo-installAcBr4U/release/build/backtrace-sys-f2f2f81888d48990/out -L native=/tmp/cargo-installAcBr4U/release/build/miniz-sys-272895524a4507ac/out -L native=/tmp/cargo-installAcBr4U/release/build/ring-751e42fec2dca871/out` (exit code: 1)
ukscone@DESKTOP-HDU73MM:~$`

building this in WSL on win10

**Comment by alexkehayias** [comment]
@ukscone Looks like I misunderstood `cargo install`—it recompiles everything rather than downloading a bin. Since there are some things compiled into the binary and I didn't want to expose them, I used environment variables which unfortunately means `cargo install` fails because they are not present on your machine :) 

The options are 1) self-host (see the docs on https://woz.sh under 'Self Hosting') or 2) I'll need to figure out some way of distributing binaries for each OS (which at the moment means macOS and Linux).

**Comment by ukscone** [comment]
I actually tried using the self-hosting method (maybe did it wrong though) and it still didn't work. i'll re-re-read the docs and see if I can workout what I did wrong if anything.

**Comment by ukscone** [comment]
ah just had a quick look at woz.sh self-hosted docs again and remembered what i didn't understand. i just want to host a simple pwa with no encryption/logins or anything just a couple of buttons and some api's like the camera and usb so didn't know what to put for things like WOZ_USER_POOL_URL & WOZ_S3_BUCKET_NAME etc.

**Comment by ukscone** [comment]
ok did the my-env thing but of course i'm sort of in a catch-22 as i can't use woz to get up the apps directory structure so can't really fill in the paths in my-env so building woz fails. could you give me an idiots guide to the contents of my-env please :)

`   Compiling rusoto_cognito_identity v0.40.0
   Compiling woz v1.3.0
error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/examples/seed-app/src/lib.rs: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:20:43
   |
20 | pub static DEFAULT_PROJECT_LIB_RS: &str = include_str!(concat!(env!("WOZ_PROJECT_ROOT"), "/examples/seed-app/src/lib.rs"));
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/styles/landing_page.css: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:22:37
   |
22 | pub static LANDING_PAGE_CSS: &str = include_str!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/styles/landing_page.css"));
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/48x48.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:31:49
   |
31 | static DEFAULT_ICON_48X48: &'static [u8; 831] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/48x48.png"));
   |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/72x72.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:32:50
   |
32 | static DEFAULT_ICON_72X72: &'static [u8; 1196] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/72x72.png"));
   |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/96x96.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:33:50
   |
33 | static DEFAULT_ICON_96X96: &'static [u8; 1538] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/96x96.png"));
   |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/144x144.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:34:52
   |
34 | static DEFAULT_ICON_144X144: &'static [u8; 2217] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/144x144.png"));
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/168x168.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:35:52
   |
35 | static DEFAULT_ICON_168X168: &'static [u8; 2566] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/168x168.png"));
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/192x192.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:36:52
   |
36 | static DEFAULT_ICON_192X192: &'static [u8; 2870] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/192x192.png"));
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/512x512.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:37:52
   |
37 | static DEFAULT_ICON_512X512: &'static [u8; 8042] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/512x512.png"));
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/152x152.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:40:52
   |
40 | static DEFAULT_ICON_152X152: &'static [u8; 2321] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/152x152.png"));
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/167x167.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:41:52
   |
41 | static DEFAULT_ICON_167X167: &'static [u8; 2489] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/167x167.png"));
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/<PATH TO WOZ REPO>/cli/resources/icons/180x180.png: No such file or directory (os error 2)
  --> /home/ukscone/.cargo/registry/src/github.com-1ecc6299db9ec823/woz-1.3.0/src/config.rs:42:52
   |
42 | static DEFAULT_ICON_180X180: &'static [u8; 2717] = include_bytes!(concat!(env!("WOZ_CLI_PROJECT_ROOT"), "/resources/icons/180x180.png"));
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 12 previous errors

error: failed to compile `woz v1.3.0`, intermediate artifacts can be found at `/tmp/cargo-installG0w46r`

Caused by:
  Could not compile `woz`.

To learn more, run the command again with --verbose.
ukscone@DESKTOP-HDU73MM:~$
`

**Comment by ukscone** [comment]
ok, think I have it sussed. clone the repo, use that as the WOZ_PROJECT_ROOT & WOZ_CLI_PROJECT_ROOT then cargo install woz 

looks like it now might be working, at least installed

**Comment by ukscone** [comment]
yes the above seemed to do it. ok failed on signup but looks like i'm at a stage where self-hosting will be ok.

`Signup failed
Caused by: Couldn't find AWS credentials in environment, credentials file, or IAM role.
ukscone@DESKTOP-HDU73MM:~$`

**Comment by alexkehayias** [comment]
Yeah there’s a lot of AWS setup to do with Incognito so maybe I’ll just work on pre-made binaries available for install. 

I’m the meantime, there’s also the ‘build’ command which will generate things locally and since they are static files you could host them wherever you’d like.

**Comment by alexkehayias** [comment]
Oops accidental close!

**Comment by alexkehayias** [comment]
I've changed the [install process](https://github.com/alexkehayias/woz#quick-start) to use pre-built binaries for supported architectures. That fixes the first issue of missing env variables when attempting to install via `cargo`. However, windows is not currently supported so it still won't work for you. 

I'm going to close this since it addresses the original issue and we can track windows support in #1.
