### ISSUE TITLE
`woz signup` fails with `Couldn't find AWS credentials`

### ISSUE THREAD

**Issue by vi** [alexkehayias/woz#6]
```
$ ~/.cargo/bin/woz  signup
Using project path /home/limited
Using config path /home/limited/woz.toml
Using home path /home/limited/.woz
Please enter the following information
Username: vi0oss
Password:
Email: vi0oss@gmail.com
Signup failed
Caused by: Couldn't find AWS credentials in environment, credentials file, or IAM role.
```

**Comment by fattenap** [comment]
I get this
```
~❯ woz signup
Using project path /Users/frank
Using config path /Users/frank/woz.toml
Using home path /Users/frank/.woz
Please enter the following information
Username: fattenap
Password:
Email: frank@zuudo.com.au
Signup failed
Caused by: Amazon SES account is in Sandbox. Verify Send-to email address or Amazon SES Account
```

**Comment by fattenap** [comment]
Doing it a second time, I get
```
~❯ woz signup
zsh: correct 'woz' to '.woz' [nyae]? n
Using project path /Users/frank
Using config path /Users/frank/woz.toml
Using home path /Users/frank/.woz
Please enter the following information
Username: fattenap
Password:
Email: frank@zuudo.com.au
Signup failed
Caused by: User already exists
```

**Comment by alexkehayias** [comment]
If you want to self host you’ll need to set up all the necessary AWS services to use this (s3, cognito, ses).

If you just want to get started using the free sandbox I set up, use the pre-made binaries (see readme).

**Comment by vi** [comment]
It is indeed the pre-made binary installed by a command-line from README:

```
$ curl -LSfs https://woz.sh/bin/install.sh | sh -s -- --target x86_64-unknown-linux-musl
install.sh: GitHub repository: https://github.com/alexkehayias/woz
install.sh: Tag: latest (v1.3.1)
install.sh: Target: x86_64-unknown-linux-musl
install.sh: Installing to: /home/limited/.cargo/bin
install.sh: ERROR woz already exists in /home/limited/.cargo/bin

$ rm ~/.cargo/bin/woz

$ curl -LSfs https://woz.sh/bin/install.sh | sh -s -- --target x86_64-unknown-linux-musl
install.sh: GitHub repository: https://github.com/alexkehayias/woz
install.sh: Tag: latest (v1.3.1)
install.sh: Target: x86_64-unknown-linux-musl
install.sh: Installing to: /home/limited/.cargo/bin

$ ~/.cargo/bin/woz  signup
Using project path /home/limited
Using config path /home/limited/woz.toml
Using home path /home/limited/.woz
Please enter the following information
Username: vi0oss
Password:
Email: vi0oss@gmail.com
Signup failed
Caused by: Couldn't find AWS credentials in environment, credentials file, or IAM role.
```

**Comment by alexkehayias** [comment]
Thanks will take a look. Maybe the keys didn’t get linked to the binary in the build

**Comment by alexkehayias** [comment]
So it looks like `CognitoIdentityProviderClient` from the underlying AWS library `rusoto` defaults to using the AWS credentials environment variables even though they are not required for calls to the Cognito API. There is anonymous credentials support in the library so I can change `woz` to not require any AWS credentials be present on the host machine when running `woz signup`. 

As a _potential_ quick fix, you might be able to add your AWS credentials to the default place `~/.aws/credentials`. Otherwise, I'll make the changes mentioned above which (I think) would fix it for you.

**Comment by alexkehayias** [comment]
@vi I made some changes which should fix signup (and some other API calls) if you don’t have any default AWS credentials on your computer. 

If you have a moment try v1.4.0 and please report back. I was able to run through fresh signup and deploy without any AWS creds.

**Comment by alexkehayias** [comment]
I’m going to close I believe this is now fixed in the latest version. Please reopen if that hasn’t resolved it for you.
