### ISSUE TITLE
Seed Awesome list

### ISSUE THREAD

**Issue by MartinKavik** [alexkehayias/woz#7]
Hi @alexkehayias ,
I've just found this project and it looks very interesting! I would be glad if you add it to [Seed Awesome list](https://github.com/seed-rs/awesome-seed-rs). 

Small feedback - It would be nice to have a section in the `woz` README about reasons _why_ we should use `woz` - i.e. what are PWWA benefits.

Thanks! And let me know when you want to add an announcement on Seed forum/chat (e.g. a new `woz` version or a super new feature is released), etc.

Martin, Seed maintainer
(feel free to close the issue)

**Comment by alexkehayias** [comment]
hiya @MartinKavik! Thanks for the ping, will do and good point on adding some more about PWAA. 

I gave a talk about the concept and introduced `woz` at SF WebAssembly awhile back—I should probably also link to it :) https://www.youtube.com/watch?v=0ySua0-c4j

**Comment by MartinKavik** [comment]
Nice! Thanks, closing the issue.
P.S. The correct link: https://www.youtube.com/watch?v=0ySua0-c4jg (missing `g` at the end 🙂)
