### ISSUE TITLE
woz.sh account creation fails

### ISSUE THREAD

**Issue by babymotte** [alexkehayias/woz#8]
I followed the Quickstart instructions at https://woz.sh/. When running `woz signup` after entering my E-Mail address, the process ended with this log message:

```
Signup failed
Caused by: Amazon SES account is in Sandbox. Verify Send-to email address or Amazon SES Account
```
When trying to signup a second time with the same credentials I get the error:

```
Signup failed
Caused by: User already exists
```

`woz setup` will now fail with `thread 'main' panicked at 'Unable to login and perform local set up: UserNotConfirmed("User is not confirmed.")`

I did not receive any confirmation E-Mail, which is consistent with the error message `woz signup` produced.

woz version: 1.4.0
Rust version: 1.44.1
OS: Arch Linux (5.7.6-arch1-1)

**Comment by alexkehayias** [comment]
Thanks for the report. Waiting to hear back from AWS on increasing the limit for my SES account. Once that's done I should be able to resend the confirmation email.

**Comment by alexkehayias** [comment]
@babymotte I've confirmed your account and emails should be working (for future signups). You should be able to complete setup with `woz setup` now. 

I'll also confirm the other users that recently ran into this issue.

**Comment by alexkehayias** [comment]
Confirmed the accounts of other Woz sandbox users that recently ran into this issue. I'm going to close this issue, but if anyone else was unable to email verify their account please reopen and I'll manually confirm. Thanks!
